/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ReferencerRouteImport } from './routes/referencer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DepartementsIndexRouteImport } from './routes/departements.index'
import { Route as DepartementsCodeRouteImport } from './routes/departements.$code'
import { Route as PrestataireIdRouteImport } from './routes/prestataire.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencerRoute = ReferencerRouteImport.update({
  id: '/referencer',
  path: '/referencer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DepartementsIndexRoute = DepartementsIndexRouteImport.update({
  id: '/departements/',
  path: '/departements/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartementsCodeRoute = DepartementsCodeRouteImport.update({
  id: '/departements/$code',
  path: '/departements/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestataireIdRoute = PrestataireIdRouteImport.update({
  id: '/prestataire/$id',
  path: '/prestataire/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/categories': typeof CategoriesRoute
  '/referencer': typeof ReferencerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/departements/$code': typeof DepartementsCodeRoute
  '/prestataire/$id': typeof PrestataireIdRoute
  '/departements/': typeof DepartementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/categories': typeof CategoriesRoute
  '/referencer': typeof ReferencerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/departements/$code': typeof DepartementsCodeRoute
  '/prestataire/$id': typeof PrestataireIdRoute
  '/departements': typeof DepartementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/annuaire': typeof AnnuaireRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/categories': typeof CategoriesRoute
  '/referencer': typeof ReferencerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/departements/$code': typeof DepartementsCodeRoute
  '/prestataire/$id': typeof PrestataireIdRoute
  '/departements/': typeof DepartementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annuaire'
    | '/auth'
    | '/carte'
    | '/categories'
    | '/referencer'
    | '/admin'
    | '/departements/$code'
    | '/prestataire/$id'
    | '/departements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annuaire'
    | '/auth'
    | '/carte'
    | '/categories'
    | '/referencer'
    | '/admin'
    | '/departements/$code'
    | '/prestataire/$id'
    | '/departements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/annuaire'
    | '/auth'
    | '/carte'
    | '/categories'
    | '/referencer'
    | '/_authenticated/admin'
    | '/departements/$code'
    | '/prestataire/$id'
    | '/departements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnuaireRoute: typeof AnnuaireRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  CategoriesRoute: typeof CategoriesRoute
  ReferencerRoute: typeof ReferencerRoute
  DepartementsCodeRoute: typeof DepartementsCodeRoute
  PrestataireIdRoute: typeof PrestataireIdRoute
  DepartementsIndexRoute: typeof DepartementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencer': {
      id: '/referencer'
      path: '/referencer'
      fullPath: '/referencer'
      preLoaderRoute: typeof ReferencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/departements/': {
      id: '/departements/'
      path: '/departements'
      fullPath: '/departements/'
      preLoaderRoute: typeof DepartementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departements/$code': {
      id: '/departements/$code'
      path: '/departements/$code'
      fullPath: '/departements/$code'
      preLoaderRoute: typeof DepartementsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestataire/$id': {
      id: '/prestataire/$id'
      path: '/prestataire/$id'
      fullPath: '/prestataire/$id'
      preLoaderRoute: typeof PrestataireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnuaireRoute: AnnuaireRoute,
  AuthRoute: AuthRoute,
  CarteRoute: CarteRoute,
  CategoriesRoute: CategoriesRoute,
  ReferencerRoute: ReferencerRoute,
  DepartementsCodeRoute: DepartementsCodeRoute,
  PrestataireIdRoute: PrestataireIdRoute,
  DepartementsIndexRoute: DepartementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
